spring.data.mongodb.host=localhost
spring.data.mongodb.port=27018
spring.data.mongodb.authentication-database=admin
spring.data.mongodb.username=root
spring.data.mongodb.password=example
spring.data.mongodb.database=productService
server.port=8081